declare let groceryList: string[];
declare const groceryDiv: HTMLElement;
declare const inputAlert: HTMLElement;
declare const groceryForm: HTMLElement;
declare const formInput: HTMLInputElement;
declare const addBtn: HTMLInputElement;
declare const groceryContainer: HTMLInputElement;
declare let editValue: boolean;
declare let clearItems: boolean;
declare const addItem: () => void;
declare const savedItems: string[];
declare const showList: () => void;
declare const clearBtn: Element | null;
declare const alertMessage: (text: string, status: string) => void;
