declare const navBar: HTMLElement;
declare const menuToggle: HTMLElement;
declare const menuLink: HTMLElement;
declare const topBtn: HTMLElement;
declare const scrollLinks: NodeListOf<Element>;
declare const date: HTMLElement;
declare const navHeight: number;
declare const menuLinkHeight: number;
declare const links: NodeListOf<HTMLAnchorElement>;
