declare const months: string[];
declare const weekdays: string[];
declare const giveawayInfo: HTMLElement;
declare const countdown: NodeListOf<Element>;
declare const expiryInfo: HTMLElement;
declare const tempDate: Date;
declare const tempYear: number;
declare const tempMonth: number;
declare const tempdate: number;
declare const futureDate: Date;
declare const countDown: () => void;
declare let tick: number;
